### ISSUE TITLE
Add support for building caelus in a docker container

### ISSUE THREAD

**Issue by hex108** [Tencent/caelus#1]
Add support for building caelus in a docker container, then we could build it on anywhere :)

/help

**Comment by ChaosJu** [comment]
> Add support for building caelus in a docker container, then we could build it on anywhere :)
> 
> /help

lgtm

**Comment by ChaosJu** [comment]
![image](https://user-images.githubusercontent.com/31558609/140755801-c1ccf931-cb43-4857-830a-98d1adf9114a.png)

**Comment by ChaosJu** [comment]
[root@VM-226-219-centos /data/caelus]# make build
./hack/format.sh
./hack/build.sh
# github.com/tencent/caelus/cmd/caelus
/usr/local/go/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/usr/bin/ld: /tmp/go-link-294188296/000010.o: unrecognized relocation (0x2a) in section `.text'
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status

make: *** [build] Error 2

**Comment by ChaosJu** [comment]
> [root@VM-226-219-centos /data/caelus]# make build ./hack/format.sh ./hack/build.sh
> 
> # github.com/tencent/caelus/cmd/caelus
> /usr/local/go/pkg/tool/linux_amd64/link: running gcc failed: exit status 1 /usr/bin/ld: /tmp/go-link-294188296/000010.o: unrecognized relocation (0x2a) in section `.text' /usr/bin/ld: final link failed: Bad value collect2: error: ld returned 1 exit status
> 
> make: *** [build] Error 2

[root@VM-226-219-centos /data/caelus]# ld -v
GNU ld (GNU Binutils) 2.26.1 

fixed by  update  GNU ld to 2.26.1

**Comment by ddongchen** [comment]
building caelus in docker image is in processing

**Comment by ddongchen** [comment]
building caelus in docker image has been supported, @hex108

**Comment by hex108** [comment]
Thanks!
