### ISSUE TITLE
不完善的README

### ISSUE THREAD

**Issue by kom0055** [Tencent/caelus#30]
因为最近在基于Caelus开始着手搞混部调度，但是看了一圈代码下来，人还是懵的。有几个问题请教下：
1. 看代码中的使用方式，yarn必须得基于K8S吗？
2. Predict之类的统筹，目前只能基于单node，没有整个集群上的资源调度吗？
3. 希望能出一个完善的傻瓜式README。感谢万分

**Comment by ddongchen** [comment]
@kom0055 您好，目前正在整理最新的readme，会给出一个完整的case。给您带来的不便，实在抱歉。
1、caelus是基于k8s混部的，可以基于caelus进行定向修改，去除k8s。
2、predict即支持基于node资源预测，也支持外部接口预测。
3、正在整理中

**Comment by ddongchen** [comment]
@kom0055 文档已更新
https://github.com/Tencent/caelus/blob/master/doc/start.md
https://github.com/Tencent/caelus/blob/master/doc/config.md
入口为：
![image](https://user-images.githubusercontent.com/18438172/146530910-c725e3ce-e97e-4402-99ee-4d3806c3b515.png)
欢迎使用caelus

**Comment by kom0055** [comment]
非常详尽，感谢
