### ISSUE TITLE
离线业务流量限制手段

### ISSUE THREAD

**Issue by GeorgeSen** [Tencent/caelus#38]
看caelus源代码，发现 pkg/caelus/qos/manager/netio/netio.go， 代码文件里面是调用linux tc指令做的流量限额， 了解到 linux TC 只能做流出流量的限额， 这个是不是代表目前caelus 只能做离线任务流出流量的限额

**Comment by ddongchen** [comment]
> 看caelus源代码，发现 pkg/caelus/qos/manager/netio/netio.go， 代码文件里面是调用linux tc指令做的流量限额， 了解到 linux TC 只能做流出流量的限额， 这个是不是代表目前caelus 只能做离线任务流出流量的限额

网络入流量控制，原生内核需要IFB虚拟网卡支持，不确定其在生产环境性能如何，目前没有支持。

**Comment by GeorgeSen** [comment]
好的  多谢了！ 另外问一下，caelus对 k8s 和 docker的版本什么要求呢？

**Comment by ddongchen** [comment]
> 好的 多谢了！ 另外问一下，caelus对 k8s 和 docker的版本什么要求呢？

没有要求。caelus的目标就是适用多场景
