### ISSUE TITLE
lighthouse make rpm 报错

### ISSUE THREAD

**Issue by GeorgeSen** [Tencent/caelus#40]
/caelus/contrib/lighthouse-plugin$ make rpm
./hack/rpm
Sending build context to Docker daemon  137.7kB
Error response from daemon: failed to parse Dockerfile: Syntax error - can't find = in "M". Must be of the form: name=value
make: *** [rpm] 错误 1

**Comment by sangshenya** [comment]
你好，我也碰到这个问题了，请问你是怎么解决的呢？

**Comment by cityofwang** [comment]
这个是因为源码里有更改，所以在make的时候， 脚本中的 GITSTAUS 会展示更改，我是直接把这个变量删掉了
