### ISSUE TITLE
Some Feedback

### ISSUE THREAD

**Issue by kom0055** [Tencent/caelus#41]
#37  这次pr, 在pkg/caelus/predict/predict_local.go 文件, 
`mem := math.Max(memStats.UsageRss-memStats.UsageTotal, 0)` 
mem永远是0, 辛苦确认下是否符合预期

**Comment by ddongchen** [comment]
@ChenLingPeng 看下？

**Comment by ChenLingPeng** [comment]
是个错误，已经在 #42 修复
