### ISSUE TITLE
离线调度器哪里去了

### ISSUE THREAD

**Issue by work-chausat** [Tencent/caelus#43]
离线调度器哪里去了，需要通过kubelet device plugin注册colocation/cpu、colocation/memory等新类型的硬件资源吗？

**Comment by ddongchen** [comment]
@work-chausat 离线调度器会单独开源，正在内部走流程。
不需要kubelet device plugin，caelus会自动增加扩展资源。caelus内部集成了混部的基本模块，可独立运行。
