### ISSUE TITLE
收集指标问题

### ISSUE THREAD

**Issue by chelei97** [Tencent/caelus#57]
tutorial.md 中提到：
Multiple  metrics supported, including cgroup metrics from cadvisor, node resource metrics, kernel metrics from eBPF, hardware events from PMU, and also Caelus collects online jobs latency from outside in the way of executable command or http server.
但代码中似乎没有看到有 kernel metrics from eBPF 这一项。

**Comment by chelei97** [comment]
并且还提到：
Now Caelus supports detecting node pressure metrics, online jobs latency, and kernel metrics which from Ebpf.
   The configuration could be found from [Rules Configuration](rules.md).
  但是 rules.md 中也没有 kernel metrics which from Ebpf 的相关配置。

**Comment by ddongchen** [comment]
eBPF指标收集当前还未集成在caelus代码中，功能还在完善。当前可通过caelus提供的标准接口获取外部提供的指标

**Comment by ddongchen** [comment]
> 并且还提到： Now Caelus supports detecting node pressure metrics, online jobs latency, and kernel metrics which from Ebpf. The configuration could be found from [Rules Configuration](rules.md). 但是 rules.md 中也没有 kernel metrics which from Ebpf 的相关配置。

eBPF指标收集当前还未集成在caelus代码中，功能还在完善。当前可通过caelus提供的标准接口获取外部提供的指标

**Comment by chelei97** [comment]
谢谢回答。
